version: '3.7'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.13
    entrypoint: '/usr/local/bin/etcd'
    command:
      - '--name=etcd'
      - '--data-dir=/etcd-data'
      - '--initial-advertise-peer-urls=http://etcd:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd:2379'
      - '--initial-cluster-token=tinycluster'
      - '--initial-cluster=etcd=http://etcd:2380'
    ports:
      - '2379:2379'
      - '2380:2380'
    volumes:
      - 'etcd:/etcd-data'
  tcapi:
    build:
      context: .
      target: build
    command:
      - '/opt/tiny-cluster/bin/bootserver'
      - 'start'
      - '-p'
      - '8080'
    ports:
      - '8080:8080'

volumes:
  etcd: